#!/bin/bash

echo "Enter the first number : "
read a

echo "Enter the second number : "
read b

echo "Addition of $a + $b = $((a+b))"

echo "Subtraction of $a - $b = $((a-b))"

echo "Multiplication of $a x $b = $((a*b))"
